<a href="https://colab.research.google.com/github/Aksa21/basic-python-for-machine-learning/blob/main/python_basics2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
PYTHON BASICS

In [1]:
#printing string
print("hi,nice to meet you")
print('Hi there')

hi,nice to meet you
Hi there


variables

In [3]:
a=20     #a integer
b=3.14115  #a cfloating point integer
c='hell0'   #a string
print(a,' ',b,' ',c)
#defining a variable:no need to mention data type

20   3.14115   hell0


Assignment

In [4]:
#assigning same values to a variable
var1=var2=var3=5
print(var1,' ',var2,' ',var3)
#assigning different values to a variable in single expression
var1,var2,var3=4,5.1,'hello'
print(var1,' ',var2,' ',var3)

5   5   5
4   5.1   hello


slicing

In [5]:
str='everyone'

print(str)                    #print whole string
print(str[0])          #print first letter
print(str[2:5])        #print 3rd to 5 th letter
print(str[2:])         #print from 3rd character
print(str[ :2])        #print upto 2nd character
print(str*2)           #print string 2 times
print(str+'TEST')      #print concatenated string

everyone
e
ery
eryone
ev
everyoneeveryone
everyoneTEST


list,tuples

In [9]:
list=[2.13,'game','token',90,'god']
print(list[0])                           #print first element in list
print(list[2:4])                        #print el from 3to 4


2.13
['token', 90]


In [10]:
tuple=(56,'lisk',67,99)
print(tuple[2:3])

(67,)


EXERCISES

In [11]:
list[0]='csdc'                 #repleces previous list first element
tuple='csdc'
print(list)
print(tuple)

['csdc', 'game', 'token', 90, 'god']
csdc


In [12]:
# Lists are ordered sets of objects, whereas dictionaries are unordered sets. But the main difference is that items in dictionaries are accessed via keys and not via their position.
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
print(tel)
print(tel['jack'])
del tel['sape']
tel['irv'] = 4127
print(tel)
print(tel.keys())
print(sorted(tel.keys()))
print(sorted(tel.values()))
print('guido' in tel)
print('jack' not in tel)

{'jack': 4098, 'sape': 4139, 'guido': 4127}
4098
{'jack': 4098, 'guido': 4127, 'irv': 4127}
dict_keys(['jack', 'guido', 'irv'])
['guido', 'irv', 'jack']
[4098, 4127, 4127]
True
False


conditioning and looping


In [19]:
for i in range(0,10):

 if i%2 == 0:

  print("square of",i," is :",i*i)

 else:

  print(i,"an odd number")


square of 0  is : 0
1 an odd number
square of 2  is : 4
3 an odd number
square of 4  is : 16
5 an odd number
square of 6  is : 36
7 an odd number
square of 8  is : 64
9 an odd number


functions

In [20]:
def area(length,width):
    return length*width
are = area(10,20)
print("Area of rectangle:",are)

Area of rectangle: 200


numpy
#a numerical package for computing in python

In [21]:
import numpy as np

a=np.array([0,8,9])
b=np.array([7,9,0])

print('Matrix A\n',a)
print('Matrix B\n',b)

print("Regular matrix addition A+B\n", a + b)

print("Addition using Broadcasting A+5\n", a + 5)   #Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

Matrix A
 [0 8 9]
Matrix B
 [7 9 0]
Regular matrix addition A+B
 [ 7 17  9]
Addition using Broadcasting A+5
 [ 5 13 14]
